[package]
name = "nativefier"
version = "0.1.0"
authors = ["Jack Mordaunt <jackmordaunt@gmail.com>"]
edition = "2018"

[dependencies]
web-view = { git = "https://github.com/Boscop/web-view.git" }
clap = "2.32.0"
serde_json = "1.0.33"
handlebars = { git = "https://github.com/sunng87/handlebars-rust.git" }