[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.compress]
command = "upx"
args = ["target/release/nativefier"]

[tasks.copy]
script_runner = "@shell"
script = [
    "cp -f -v target/release/nativefier $HOME/.cargo/bin/nativefier"
]

[tasks.install]
dependencies = [
    "build",
    "copy",
]

[tasks.install-tiny]
dependencies = [
    "build",
    "compress",
    "copy",
]