[package]
name = "cli"
version = "0.2.0"
authors = ["Jack Mordaunt <jackmordaunt@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
url = "2.1.0"
log = "0.4.8"
pretty_env_logger = "0.3.1"

[dependencies.nativefier]
path = "../nativefier"